mongodb:
    image: fiware/tutorials.tourguide-app.restaurant-data:20160201
    hostname: mongodb
    expose:
        - "27017"
    command: --smallfiles

orion:
    image: fiware/orion:0.26.1
    hostname: orion
    links:
        - mongodb
    expose:
        - "1026"
    ports:
        - "1026:1026"
    command: -dbhost mongodb

authzforce:
    image: fiware/authzforce-ce-server:latest
    hostname: authzforce
    expose:
        - "8080"
    # remove predefined domains before starting tomcat
    command: bash -c "rm -rfv /opt/authzforce-ce-server/data/domains/* ; exec catalina.sh run"

idm:
    image: bitergia/idm-keyrock:5.1.0
    hostname: idm
    links:
        - authzforce
    volumes:
        - /config
    expose:
        - "5000"
    environment:
        - APP_NAME=TourGuide
        - AUTHZFORCE_VERSION=4.4.0

pepwilma:
    image: bitergia/pep-wilma:4.3.0
    hostname: pepwilma
    links:
        - orion
        - idm
        - authzforce
    volumes_from:
        - idm
    expose:
        - "1026"
    environment:
        - APP_HOSTNAME=orion
        - APP_PORT=1026
        - AUTHZFORCE_VERSION=4.4.0

idasiotacpp:
    image: bitergia/idas-iota-cpp:1.2.0
    hostname: idasiotacpp
    links:
        - mongodb
        - orion
    expose:
        - "8080"
        - "8081"

ul20client:
    image: bitergia/ul20-client:latest
    hostname: ul20client
    links:
        - orion
        - idasiotacpp:iota
    command: --acpi
    environment:
        - IOTA_PORT=8080
        - UL20_SERVICE_NAME=tourguideul20

cygnus:
    image: bitergia/cygnus:develop
    links:
        - orion
    #    - mariadb
    expose:
        - "5001"
        - "5002"
        - "5003"
        - "5050"
        - "6001"
    environment:
        - CKAN_API_KEY=648b4204-feb6-4f5c-b9c4-813c48319669
        - COSMOS_USER=acs
        - COSMOS_PASSWORD=
    #    - MYSQL_HOST=mariadb
    #    - MYSQL_PORT=3306
    #    - MYSQL_USER=root
    #    - MYSQL_PASSWORD=bitergia
    volumes:
        - ~/devel/fiware/tutorials.TourGuide-App/docker/cygnus/subscriptions:/opt/subscribe
        - ~/devel/fiware/tutorials.TourGuide-App/docker/cygnus/conf:/config

cep-proton:
    image: bitergia/cep-proton:master
    hostname: cep-proton
    expose:
        - "8080"
        - "8686"
        - "3002"
        - "3302"
    ports:
        - "8080:8080"
    links:
        - orion

tourguide:
    image: fiware/tutorials.tourguide-app:latest
    hostname: tourguide
    links:
        - orion
        - idm
        - pepwilma
        - idasiotacpp:idas
        - cep-proton
    environment:
        - ORION_HOSTNAME=pepwilma
        - ORION_NO_PROXY_HOSTNAME=orion
        - ORION_PORT=1026
        - ORION_PEP_ENABLED=true
        - IDAS_PORT=8080
        - ORION_SUBSCRIPTIONS_ENABLED=false
        - SENSORS_GENERATION_ENABLED=false
        - SENSORS_FORCED_UPDATE_ENABLED=false
        - CEP_ENABLED=false
    volumes_from:
        - idm
    # volumes:
    #     - ~/devel/fiware/tutorials.TourGuide-App:/home/tourguide/tutorials.TourGuide-App
